### PR TITLE
move-out-crates

### PR DESCRIPTION
**Pull request by sunce86**
This PR prepares repo so it can be referenced from other repos (no new functionality added, only moves).

1. Updates `contracts` crate to the newest version from https://github.com/cowprotocol/services
2. Renames `sources` crate to `liquidity-sources` for clarification
3. Moves out all crates from `crates` folder and defines all crate names explicitly in `workspace` file so they can be used as dependency in external projects (I am not 100% sure this is necessary, but I did not find a way to add dependency if it is not explicitly named in the `workspace` toml file).

### CODE REVIEW

**Review by MartinquaXD — COMMENTED** [review]
The diffs show a bunch of contracts added for Goerli as well as new subgraph and univ3 code. Did you maybe branch the changes off of the wrong commit?

**Comment by sunce86** [comment]
> The diffs show a bunch of contracts added for Goerli as well as new subgraph and univ3 code. Did you maybe branch the changes off of the wrong commit?

Some git glitch happened. For some reason old files were not tracked as deleted. I think I fixed it now.

**Comment by vkgnosis** [comment]
> 3\. (I am not 100% sure this is necessary, but I did not find a way to add dependency if it is not explicitly named in the `workspace` toml file).

I couldn't confirm this locally.

```toml
[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-a = { path = "../workspace-a/crates/lib-a" }
database = { git = "https://github.com/cowprotocol/services.git" }
```

It worked for both a local dependency and a git dependency where the workspace Cargo.toml uses `crates/*`.

**Comment by sunce86** [comment]
> > 3. (I am not 100% sure this is necessary, but I did not find a way to add dependency if it is not explicitly named in the `workspace` toml file).
> 
> I couldn't confirm this locally.
> 
> ```toml
> [package]
> name = "consumer"
> version = "0.1.0"
> edition = "2021"
> 
> [dependencies]
> lib-a = { path = "../workspace-a/crates/lib-a" }
> database = { git = "https://github.com/cowprotocol/services.git" }
> ```
> 
> It worked for both a local dependency and a git dependency where the workspace Cargo.toml uses `crates/*`.

This is really weird, because I am convinced this was the first thing I tried and it didn't work (now it works). Anyway, I think this PR changes still stand since I expect `contracts` crate to be removed from this repo, so `liquidity-sources` will be the only crate therefore making `workspace` irrelevant eventually.

**Review by vkgnosis — APPROVED** [review]

**Review by MartinquaXD — APPROVED** [review]

**Pull request merged**
